name: Release Extension
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run build:ext

      - name: Zip Extension
        run: |
          cd packages/ext/dist
          zip -r ../../../chess-tui-extension.zip ./*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: chess-tui-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
